import { getContract } from "thirdweb";
import { chain, client } from "../client";

//const CONTRACT_ADDRESS = "0xF222BcA8d89c3fB5f4788c9b7602dd367A8C2B3C";
//const CONTRACT_ADDRESS = "0x8019A6Ad4c38504C584668711B0ADD07e055cA36";
//const CONTRACT_ADDRESS = "0x20d3d6705d1D3948714889fd900D56269404D73E";
const CONTRACT_ADDRESS = "0x243bf70285ECb72B6E01f3be7085f50CC34a054b";

const proxyAbi = [
    {"type":"constructor","inputs":[],"stateMutability":"nonpayable"},{"type":"fallback","stateMutability":"nonpayable"},{"type":"function","name":"balanceOf","inputs":[{"name":"_addr","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"getDelegation","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"getNumberOfProperties","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"getPositionOf","inputs":[{"name":"_propertyID","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"tuple","internalType":"struct Proxy.Position","components":[{"name":"x","type":"uint256","internalType":"uint256"},{"name":"y","type":"uint256","internalType":"uint256"}]}],"stateMutability":"view"},{"type":"function","name":"name","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"function","name":"ownerOf","inputs":[{"name":"_propertyID","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"setDelegation","inputs":[{"name":"_impl","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"symbol","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"error","name":"AUTHORIZATION_DENIED","inputs":[]},{"type":"error","name":"DELEGATION_FAILED","inputs":[]}
] as const;

const worldAbi = [
    {"type":"constructor","inputs":[{"name":"_name","type":"string","internalType":"string"},{"name":"_symbol","type":"string","internalType":"string"}],"stateMutability":"nonpayable"},{"type":"function","name":"balanceOf","inputs":[{"name":"_addr","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"getNumberOfProperties","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"getPositionOf","inputs":[{"name":"_propertyID","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"tuple","internalType":"struct World.Position","components":[{"name":"x","type":"uint256","internalType":"uint256"},{"name":"y","type":"uint256","internalType":"uint256"}]}],"stateMutability":"view"},{"type":"function","name":"isPositionAvailable","inputs":[{"name":"_x","type":"uint256","internalType":"uint256"},{"name":"_y","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},{"type":"function","name":"mint","inputs":[{"name":"_x","type":"uint256","internalType":"uint256"},{"name":"_y","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"name","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"function","name":"ownerOf","inputs":[{"name":"_propertyID","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"symbol","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"error","name":"AUTHORIZATION_DENIED","inputs":[]},{"type":"error","name":"NOT_VALID_ADDRESS","inputs":[]},{"type":"error","name":"POSITION_ALREADY_USED","inputs":[{"name":"","type":"uint256","internalType":"uint256"},{"name":"","type":"uint256","internalType":"uint256"}]}
] as unknown as any[];

export const CONTRACT = getContract({
    client: client,
    chain: chain,
    address: CONTRACT_ADDRESS,
    abi: worldAbi,
})